### ISSUE TITLE
error problem

### ISSUE THREAD

**Issue by CnBDM-Su** [WeiyuCheng/FIA-KDD-19#1]
I want to do some experiment on your code, so I ran your code and encounter an error 
InvalidArgumentError: indices[5] = 3705 is not in [0, 3703)
	 [[node embedding_layer/item_bias (defined at ..\influence\matrix_factorization.py:107) ]]
I checked the input, do not find the input of shape is 3705.
do you know how to fix it? 
Thanks

**Comment by WeiyuCheng** [comment]
Hello, did you use the tensorflow-gpu==1.4.0 version?

**Comment by CnBDM-Su** [comment]
I used tensorflow-1.4.0 without gpu, because my hardware is not compatible for the nvidia cuda 8.0.

**Comment by CnBDM-Su** [comment]
I have solved the problem by increasing the item_num to 3706 , but i don't understand why the unique item num does not fit the size of the embedding.

**Comment by WeiyuCheng** [comment]
Hello, I found this was caused by an error in the uploaded dataset. I have made a quick fix by modifying the calculation of num_items. This problem should have been solved.

**Comment by CnBDM-Su** [comment]
OK, Thanks
